### ISSUE TITLE
The regex tutorial is wrong

### ISSUE THREAD

**Issue by FerdinandBeaman** [learn-co-curriculum/dsc-introduction-to-regular-expressions#2]
## Link to Canvas

https://learning.flatironschool.com/courses/6224/pages/introduction-to-regular-expressions?module_item_id=530192

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [x ] Instructions unclear
- [ ] Other (explain below)

## Describe the Issue
The code below doesn't work. What should be in compile() is "pattern", and findall() should have "sentence" inside the brackets.
```
import re
sentence = 'he said that she said "hello".'
pattern = 'he'
p = re.compile(sentence)
p.findall() # Output will be ['he', 'he, 'he']
```

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for brining this to our attention. We'll take a look.

**Comment by bpurdy-ds** [comment]
You are correct!

**Comment by bpurdy-ds** [comment]
Fixed.

**Comment by FerdinandBeaman** [comment]
It's kinda cool to be the reason why a difference was made, however small
